### ISSUE TITLE
Devise 3.2.0 incompatibility

### ISSUE THREAD

**Issue by toymachiner62** [noiseunion/devise-basecamper#12]
I'm currently getting this error:

``` ruby
Bundler could not find compatible versions for gem "devise":
  In Gemfile:
    devise-basecamper (>= 0) ruby depends on
      devise (~> 2.0.4) ruby

    devise (3.2.0)
```

My gemfile contains:

``` ruby
gem 'devise'            # authentication
gem 'devise-basecamper' # For subdomain authentication
```

Looking at the file below, it seems that by adding `gem 'devise-basecamper` and running bundle install, it's not looking at the latest code. 
https://github.com/toymachiner62/devise-basecamper/blob/master/devise-basecamper.gemspec

Is my assumption correct and how do we update it so i don't have to point my gemfile to a github repo?

**Comment by maltemuth** [comment]
It seems that this has been resolved - the mentioned lines in the Gemfile work for me. (with devise 3.2.1)

**Comment by noiseunion** [comment]
yes!  I thought this issue was hooked up to the pull request that got merged. :)  Closing it! Thanks again @toymachiner62  for the PR.

**Comment by toymachiner62** [comment]
No problem sorry for not linking this.
