### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by frecklebit** [noiseunion/devise-basecamper#15]
When you register a new user, their confirmation email doesn't have the right subdomain.

Better yet, how does it even work with user registration and setting up the account?

**Comment by noiseunion** [comment]
Hey @adamcole83, sorry for the delay in responding.  I don't know if we have ever used this with confirmation emails, so i'll have to look into this.  Or if you have time, feel free to submit a pull request.

In regards to user registration, you need to create the account first with the subdomain and then the user.  I would do this with a custom form object to handle creating the appropriate models in sequence.  You could also achieve the same result using accepts_nested_attributes on your account model for the user, but this can be a bigger pain in the rear.  I would go with a form object.

**Comment by noiseunion** [comment]
@adamcole83 did you ever get this issue figured out? Can I close this?

**Comment by frecklebit** [comment]
Yes I have, thank you.
