### ISSUE TITLE
Superuser bypass Domain check

### ISSUE THREAD

**Issue by frecklebit** [noiseunion/devise-basecamper#16]
How would I bypass domain check for superusers?

**Comment by noiseunion** [comment]
hey @adamcole83, can you give me a little more detail on what you are looking for?

**Comment by noiseunion** [comment]
@adamcole83 do you still need assistance in this?

**Comment by frecklebit** [comment]
Yes I do, sorry. I have a superuser that I'd like to not authenticate on subdomain but have the ability to access the subdomain account. How would I do that?

**Comment by noiseunion** [comment]
You should be able to do this using a separate user devise model "SuperUser" and then don't include the basecamper stuff in that devise model.  Then you can use that guy as your "Super User".  Would this work for your use case?

For the ability to access the subdomain account, are you looking for like user spoofing?

**Comment by noiseunion** [comment]
@adamcolejenkins has this been resolved for you?

**Comment by frecklebit** [comment]
It was, thank you.
