### ISSUE TITLE
How to implement registrable?

### ISSUE THREAD

**Issue by milani** [noiseunion/devise-basecamper#18]
What if I want to force users to sign up into a specific subdomain?

In my application, users belong to many organizations and organizations have many users. Each organization is distinguished by a subdomain. When a user wants to register, he/she should provide the subdomain of his/her organization. I think there should be a registrable implementation for basecamper.

**Comment by noiseunion** [comment]
So you're saying that a user can register under an organization, but then that same user can belong to more than one organization?  Is that correct?

**Comment by milani** [comment]
Yes. The user can signup in more than one organization. Actually, renaming "organization" to "group" would make it more understandable.

**Comment by noiseunion** [comment]
hmmmm...that could be more complicated than just registration.  The idea with basecamper is to scope users specifically to a single organization.  I would have to know more about your schema to understand how basecamper could work for you in this particular scenario.
