### ISSUE TITLE
reusable emails across subdomains

### ISSUE THREAD

**Issue by Wurren** [noiseunion/devise-basecamper#19]
Hey,

Just came across an issue where I have two subdomains _agency1_ and _agency2_, and I have one user creating each account with the same email address (or adding more team members who have the same email for each account afterward). However I get the error  "email has already been taken"

Is there a way around this with basecamper, or do I have to define my own validation and remove :validatable from the model?

**Comment by noiseunion** [comment]
Hey @Wurren sorry for the late reply.  I don't get in here as often as I would like.  Have you solved your issue?  The email addresses should be getting scoped to subdomain.  I'm not sure why you were getting the error you were.  Let me know if you still need help.

**Comment by Wurren** [comment]
No problem!

Still having the problem unfortunately. I have the Account form set up that accepts nested attributes for the User account. I keep getting "has already been taken". Theres no other validation on the User model and I've removed the "unique" flag from the Migration table for users on the email column.

On POST I get this logged out:

```
Started POST "/signup" for 127.0.0.1 at 2015-07-29 23:35:53 +0100
Processing by AccountsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"UIpfaW1ZSEhrVQO633/z9anlq3jK8HfEihaVjuAssXjaOrM/6LBHwrjOrPr1UjQu+KKyZ19VqasHmEhBkCY0fw==", "account"=>{"subdomain"=>"test", "users_attributes"=>{"0"=>{"email"=>"test@test.ie", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}}, "commit"=>"Sign up"}
   (0.1ms)  BEGIN
  User Exists (0.3ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'test@test.ie' LIMIT 1
  Account Exists (0.1ms)  SELECT  1 AS one FROM `accounts` WHERE `accounts`.`subdomain` = BINARY 'test' LIMIT 1
  CACHE (0.0ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'test@test.ie' LIMIT 1
   (0.1ms)  ROLLBACK
  Rendered accounts/new.haml within layouts/home (258.1ms)
Completed 200 OK in 383ms (Views: 287.5ms | ActiveRecord: 0.7ms)
```

Not sure why this could be happening, unless devise is using its default validation.

**Comment by noiseunion** [comment]
Hey @Wurren ,

Sorry I have been so slow, I have just got out of a really long contract and finally have some time to look at this stuff again.  Are you still dealing with this issue or did you get something figured out?

**Comment by Wurren** [comment]
Hey @noiseunion,

Also sorry for the slow reply. I looked into this and figured out why this is happening. Firstly, the devise :validatable module is using validations which don't scope the uniqueness of the email to the account.

This means when creating additional users after creating an account you cant add users which may also be on other accounts.

https://github.com/plataformatec/devise/blob/master/lib/devise/models/validatable.rb#L30

Theres also the issue that the migration created for devise has a unique flag created on the index

https://github.com/plataformatec/devise/blob/master/lib/generators/active_record/templates/migration.rb#L13

A quick solution is to remove the unique flag from the migrations and then remove the devise validations module from the model, and copy over the devise validations with alterations (and associated methods) from the module into the model which works ok.

I did however fork the repo to test out adding a validatable override module, but it doesn't seem to be working. Maybe you can help:

devise-basecamper.rb

```
require 'devise'
require 'devise-basecamper/version'
require 'devise-basecamper/devise/models/authenticatable'
require 'devise-basecamper/basecamper'
require 'devise-basecamper/authentication'
require 'devise-basecamper/recoverable'
require 'devise-basecamper/confirmable'
require 'devise-basecamper/validatable'

## Establish the namespace --------------------------------
module DeviseBasecamper
end

## Add the model to devise --------------------------------
Devise.add_module(:basecamper,
  :strategy   => false,
  :route      => :session,
  :controller => :sessions,
  :model      => 'devise-basecamper/model'
)
```

model.rb

```
module Devise
  module Models
    module Basecamper
      extend ActiveSupport::Concern
      included do
        include DeviseBasecamper::Basecamper
        include DeviseBasecamper::Authentication
        include DeviseBasecamper::Recoverable
        include DeviseBasecamper::Confirmable
        include DeviseBasecamper::Validatable
      end
    end
  end
end
```

validatable.rb

```
module DeviseBasecamper
  module Validatable
    module ClassMethods
      def self.included(base)
        base.extend ClassMethods
        assert_validations_api!(base)
        base.class_eval do
          validates_presence_of   :email, if: :email_required?
          validates_uniqueness_of :email, allow_blank: true, if: :email_changed?, scope: basecamper[:scope_field]
          validates_format_of     :email, with: email_regexp, allow_blank: true, if: :email_changed?

          validates_presence_of     :password, if: :password_required?
          validates_confirmation_of :password, if: :password_required?
          validates_length_of       :password, within: password_length, allow_blank: true
        end
      end
    end
  end
end
```

Cheers

**Comment by noiseunion** [comment]
hey @Wurren thanks for digging in!  I have had issues with the validations devise provides as well.  In fact I am pretty sure we just started removing them by default.  Probably be a good thing to note in the current documentation somewhere.

I'm thinking maybe setting up a generator for creating a migration to fix the database would be cool and the override is also a good idea.  I'll see if I can't take a look late next week at it.  LMK if you make any further process in the meantime.

**Comment by noiseunion** [comment]
I am going to close this for now since it appears to be a dead issue
