### ISSUE TITLE
Incompatible with Devise 2.1.2

### ISSUE THREAD

**Issue by adpande** [noiseunion/devise-basecamper#2]
Getting the following error when using with Devise 2.1.2:

Bundler could not find compatible versions for gem "orm_adapter":
  In Gemfile:
    devise (~> 2.1.2) ruby depends on
      orm_adapter (~> 0.1) ruby

```
devise-basecamper (~> 0.1.1) ruby depends on
  orm_adapter (0.0.7)
```

Thanks in advance.

Regards,

**Comment by noiseunion** [comment]
fixed the dependencies.  I've got it installing with Devise 2.1.2...I have not yet tested it though.  I will post back, or if you find things to be better, let me know. :)

**Comment by adpande** [comment]
Thanks JD. I did fork and fixed the dependency. It got installed with no issues. But issue#1 still remains.

**Comment by noiseunion** [comment]
cool.  I'm working on getting the new project setup far enough for me to test it out, I'll keep you posted on the config issues as I go.  I'm going to close this issue out.
