### ISSUE TITLE
Authenticate account's owner without the need to type the subdomain in URL

### ISSUE THREAD

**Issue by juliobetta** [noiseunion/devise-basecamper#6]
I've been thinking ... if I am the account's owner, I dont have to type the subdomain in the URL everytime I want to login. Therefore, once the account model has an user_id attribute (the account's owner), the system should, in first place, find the user by its email, get the id and then find the account through user_id.

This funcionality is implemented on wufoo.com.

What do you think about that? Any ideas on how to implement it on devise-basecamper?

thanks.. ;)

**Comment by noiseunion** [comment]
I'm not sure I'm understanding what you are wanting to do.  Search for users first and get the account from there?  That is how devise already works out-of-the-box.

**Comment by juliobetta** [comment]
Take a look at
http://help.wufoo.com/app/answers/detail/a_id/5724/~/logging-into-wufoo-will-allow-you-to-access-the-administrative-features-of-wufoo
and you will understand what I'm talking about.
Em 01/12/2012 13:06, "JD Hendrickson" notifications@github.com escreveu:

**Comment by noiseunion** [comment]
Yeah, that is what I was thinking you meant.  This is not something that you would put into devise-basecamper, this would just be a strategy for implementing devise.  devise-basecamper would be a part of that strategy, but ONLY for managing the account users.  The account owner, I would configure to be a different devise model entirely, and use standard devise methods for authentication.

so something like:

``` ruby
class AccountOwner
    devise  :database_authenticatable,
               :recoverable,
               :trackable
    ...
end
```

This would setup the AccountOwner "role" to use standard devise configurations for authentication to your application.  Would have completely different views as well, however...they could ONLY sign in from those views.

``` ruby
class AccountUser
    devise  :registerable,
                 :basecamper
    ...
end
```

The AccountUser "role" would now be governed by the devise-basecamper gem and require the user to login with the appropriate subdomain.

As best I can tell, this would give you the functionality you are looking for.  Wufoo has one login for account owners (secure.wufoo.com/login) and another for account users (subdomain.wufoo.com/login).

All of this could be done with NO changes to devise-basecamper.  I am actually doing something similar in a different project.

**Comment by juliobetta** [comment]
good ideia! I'll do it when I get home tonight!
tks! =D

On Mon, Dec 3, 2012 at 1:06 PM, JD Hendrickson notifications@github.comwrote:

> Yeah, that is what I was thinking you meant. This is not something that
> you would put into devise-basecamper, this would just be a strategy for
> implementing devise. devise-basecamper would be a part of that strategy,
> but ONLY for managing the account users. The account owner, I would
> configure to be a different devise model entirely, and use standard devise
> methods for authentication.
> 
> so something like:
> 
> class AccountOwner
>     devise  :database_authenticatable,
>                :recoverable,
>                :trackable
>     ...end
> 
> This would setup the AccountOwner "role" to use standard devise
> configurations for authentication to your application. Would have
> completely different views as well, however...they could ONLY sign in from
> those views.
> 
> class AccountUser
>     devise  :registerable,
>                  :basecamper
>     ...end
> 
> The AccountUser "role" would now be governed by the devise-basecamper gem
> and require the user to login with the appropriate subdomain.
> 
> As best I can tell, this would give you the functionality you are looking
> for. Wufoo has one login for account owners (secure.wufoo.com/login) and
> another for account users (subdomain.wufoo.com/login).
> 
> All of this could be done with NO changes to devise-basecamper. I am
> actually doing something similar in a different project.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/digitalopera/devise-basecamper/issues/6#issuecomment-10956485.

## 

JulioBêtta
Linux User #518828

**Comment by noiseunion** [comment]
ok to close this out?

**Comment by juliobetta** [comment]
Ok, tks!
Em 06/12/2012 21:15, "JD Hendrickson" notifications@github.com escreveu:
