### ISSUE TITLE
Incompatible with Devise 2.2.2

### ISSUE THREAD

**Issue by riverock** [noiseunion/devise-basecamper#7]
Getting the following error when using with devise 2.2.2:

Bundler could not find compatible versions for gem "devise":
  In Gemfile:
    devise-basecamper (>= 0) ruby depends on
      devise (~> 2.1.0) ruby

```
devise (2.2.2)
```

Are there plans to upgrade devise-basecamper to work with devise 2.2.2?

Regards,
Denis

**Comment by noiseunion** [comment]
I haven't tested it at all yet.  I can try and do that soon, or if you would like to fork it and give it a try that would be cool to. :smile:

**Comment by riverock** [comment]
I created a fork, changed the Devise dependency to gem.add_dependency('devise', '~> 2.2.0'), and upped the gem's version to 0.2.2.  

Everything appears to be working fine, haven't run into any issues.  I can't say for sure that my app is testing every nook and cranny in devise-basecamper, but so far so good.

**Comment by noiseunion** [comment]
excellent!!!  When you feel good about it, shoot me a pull request and we'll get it branched and do some more testing.  Thanks for helping out!

**Comment by noiseunion** [comment]
a fix was pushed up by @kagd for this so I am going to close this issue.
